/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * OpenAPI spec version: 1.0.11
 */

export interface SearchedProduct {
  /** Цена со скидочной картой */
  discountCardPrice?: number;
  /** Название продукта */
  name?: string;
  /** Список фотографий продукта */
  photos?: string[];
}
