/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * OpenAPI spec version: 1.0.11
 */

export type GetAllOrFilteredProductsParams = {
  /**
   * Minimum price for filtering
   */
  min?: number;
  /**
   * Maximum price for filtering
   */
  max?: number;
  /**
   * ID of country for filtering
   */
  countryId?: number;
  /**
   * Vegan-property for filtering
   */
  vegan?: boolean;
  /**
   * Price-sorting by increase / decrease / categories
   */
  sort?: string;
};
