/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * OpenAPI spec version: 1.0.11
 */

export type GetSearchedProductsParams = {
  /**
   * Text from CatalogInput
   */
  inputText: string;
};
