/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * OpenAPI spec version: 1.0.11
 */
import type { ProductCategory } from "./productCategory";
import type { ProductCountry } from "./productCountry";
import type { ProductReviewsItem } from "./productReviewsItem";

export interface Product {
  /** Доступность продукта */
  availability?: boolean;
  /** Бренд продукта */
  brand?: string;
  /** Категория продукта */
  category?: ProductCategory;
  /** Страна-производитель продукта */
  country?: ProductCountry;
  /** Описание продукта */
  description?: string;
  /** Цена со скидочной картой */
  discountCardPrice?: number;
  /** Ингредиенты продукта */
  ingredients?: string;
  /** Название продукта */
  name?: string;
  /** Список фотографий продукта */
  photos?: string[];
  /** Цена продукта */
  price?: number;
  /** Уникальный идентификатор продукта */
  product_id?: number;
  /** Рейтинг продукта */
  rating?: number;
  reviews?: ProductReviewsItem[];
  /** Веганский продукт или нет */
  vegan?: boolean;
  /** Вес продукта */
  weight?: number;
}
