/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * OpenAPI spec version: 1.0.11
 */

export interface Review {
  /** ID продукта, для которого создаётся отзыв */
  product_id?: string;
  /** Оценка продукта */
  rating?: number;
  /** Содержание отзыва */
  text?: string;
  /** ID пользователя, который создаёт отзыв */
  user_id?: string;
  /** Имя пользователя, который создаёт отзыв */
  username?: string;
}
